from django.contrib.auth.models import User
from social_core.exceptions import AuthForbidden

def verifica_usuario_existente(strategy, details, backend, uid, user=None, *args, **kwargs):
    email = details.get('email')
    print("üìß E-MAIL recebido:", email)

    if not email:
        print("‚ö†Ô∏è Email n√£o fornecido.")
        raise AuthForbidden(backend)

    try:
        user = User.objects.get(email=email)
    except User.DoesNotExist:
        print("‚õî Usu√°rio n√£o encontrado no banco:", email)
        raise AuthForbidden(backend)

    print("‚úÖ Usu√°rio autorizado:", user.username)
    return {'user': user}
